In [1]:
#Library

%matplotlib inline
    
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp
import astropy
import pandas as pd

from IPython.display import Image,HTML,IFrame
from astropy.io import fits as pyfits
import urllib.request

#import gt_apps as gt

import astropy.table as table
pd.set_option('display.max_rows', None)

import sys
import os
os.environ['LVDBDIR'] = '../local_volume_database'
sys.path.append('../local_volume_database')

import local_volume_database as lvdb

# List all *.csv files

In [2]:
## Input for latex table, load locally

#Read through *.csv file. These are Dwarf Galaxies.
comb_all_local = table.Table.read('../local_volume_database/data/dwarf_all.csv') 
comb_local_field = table.Table.read('../local_volume_database/data/dwarf_local_field.csv')
comb_local_field_distant = table.Table.read('../local_volume_database/data/dwarf_local_field_distant.csv')

#Read through *.csv file. These are Globular Clusters.
comb_gc_ambiguous = table.Table.read('../local_volume_database/data/gc_ambiguous.csv')
comb_gc_dwarf_hosted = table.Table.read('../local_volume_database/data/gc_dwarf_hosted.csv')
comb_gc_harris = table.Table.read('../local_volume_database/data/gc_harris.csv')
comb_mw_new = table.Table.read('../local_volume_database/data/gc_mw_new.csv')
comb_other = table.Table.read('../local_volume_database/data/gc_other.csv')

# For dwarf_all.csv file
This file should list all the dwarf galaxies, along with their host.

In [3]:
#Comb through file in 'host' category, only accept dwarfs with * as host
dsph_mw = comb_all_local[comb_all_local['host'] == 'mw']

## All Dwarf Galaxies in LVDB

In [4]:
#Find all dwarf galaxies with declination above 20 degrees above/below galactic plane

test_system = comb_all_local[abs(comb_all_local['dec']) >= 20.0]
print(len(test_system))
#print(test_system)

#I think I need to be a little more restrictive, this is a lot lol

659

In [5]:
lvdb.add_column(test_system,'location','name_discovery', col_type='U25')

In [6]:
# Convert the column slice to a pandas dataframe for standard viewing
test_system['key', 'name', 'ra', 'dec', 'host'].to_pandas()

,key,name,ra,dec,host
0,antlia_2,Antlia II,143.807900,-36.699100,mw
1,bootes_3,Bootes III,209.300000,26.800000,mw
2,bootes_4,Bootes IV,233.689000,43.726000,mw
3,bootes_5,Bootes V,213.909000,32.914000,mw
4,canes_venatici_1,Canes Venatici I,202.009100,33.552100,mw
5,canes_venatici_2,Canes Venatici II,194.292700,34.322600,mw
6,carina_1,Carina,100.406500,-50.959300,mw
7,carina_2,Carina II,114.106600,-57.999100,lmc
8,carina_3,Carina III,114.629800,-57.899700,lmc
9,carina_4,Carina IV,104.046000,-63.319000,mw
10,centaurus_1,Centaurus I,189.590800,-40.904300,mw
11,columba_1,Columba I,82.856960,-28.042530,mw
12,coma_berenices_1,Coma Berenices,186.745400,23.906900,mw
13,draco_1,Draco,260.068400,57.918500,mw
14,draco_2,Draco II,238.198333,64.565278,mw
15,eridanus_2,Eridanus II,56.092500,-43.532900,mw
16,fornax_1,Fornax,39.958300,-34.499700,mw
17,grus_1,Grus I,344.166000,-50.168000,mw
18,grus_2,Grus II,331.025000,-46.442000,mw
19,horologium_1,Horologium I,43.875500,-54.117400,lmc
20,horologium_2,Horologium II,49.131000,-50.009000,mw
21,hydra_2,Hydra II,185.428600,-31.972800,mw
22,hydrus_1,Hydrus I,37.389000,-79.308900,lmc
23,leo_2,Leo II,168.362700,22.152900,mw
24,leo_6,Leo VI,171.077000,24.874000,mw
25,leo_minor_1,Leo Minor I,164.261000,28.875000,mw
26,lmc,LMC,78.760000,-69.190000,mw
27,pegasus_4,Pegasus IV,328.539000,26.620000,mw
28,phoenix_2,Phoenix II,354.991900,-54.401900,lmc
29,phoenix_3,Phoenix III,26.711000,-41.428000,mw
30,pictor_1,Pictor I,70.947500,-50.283056,mw
31,pictor_2,Pictor II,101.175000,-59.901000,lmc
32,reticulum_2,Reticulum II,53.920300,-54.051300,lmc
33,reticulum_3,Reticulum III,56.360000,-60.450000,mw
34,sagittarius_1,Sagittarius,284.095166,-30.549887,mw
35,sculptor_1,Sculptor,15.018300,-33.718600,mw
36,segue_2,Segue 2,34.822600,20.162400,mw
37,smc,SMC,16.250000,-72.420000,lmc
38,triangulum_2,Triangulum II,33.315500,36.169100,mw
39,tucana_2,Tucana II,342.979600,-58.568900,mw
40,tucana_3,Tucana III,359.107500,-59.583320,mw
41,tucana_4,Tucana IV,0.717000,-60.830000,mw
42,tucana_5,Tucana V,354.347000,-63.266000,mw
43,ursa_major_1,Ursa Major I,158.770600,51.947900,mw
44,ursa_major_2,Ursa Major II,132.872600,63.133500,mw
45,ursa_minor_1,Ursa Minor,227.242000,67.222100,mw
46,willman_1,Willman 1,162.343600,51.050100,mw
47,andromeda_01,Andromeda I,11.415420,38.037500,m_031
48,andromeda_02,Andromeda II,19.111670,33.435280,m_031
49,andromeda_03,Andromeda III,8.878750,36.498890,m_031
50,andromeda_05,Andromeda V,17.572920,47.628330,m_031
51,andromeda_06,Andromeda VI,357.945420,24.582500,m_031
52,andromeda_07,Andromeda VII,351.639580,50.680000,m_031
53,andromeda_09,Andromeda IX,13.222500,43.199170,m_031
54,andromeda_10,Andromeda X,16.647500,44.807500,m_031
55,andromeda_11,Andromeda XI,11.582080,33.802780,m_031
56,andromeda_12,Andromeda XII,11.867920,34.377220,m_031
57,andromeda_13,Andromeda XIII,12.962500,33.004440,m_031
58,andromeda_14,Andromeda XIV,12.895830,29.689720,m_031
59,andromeda_15,Andromeda XV,18.576250,38.119720,m_031
60,andromeda_16,Andromeda XVI,14.876250,32.376111,m_031
61,andromeda_17,Andromeda XVII,9.276250,44.323060,m_031
62,andromeda_18,Andromeda XVIII,0.560250,45.087722,NaN
63,andromeda_19,Andromeda XIX,4.893750,35.044720,m_031
64,andromeda_20,Andromeda XX,1.877500,35.126940,m_031
65,andromeda_21,Andromeda XXI,358.699580,42.470560,m_031
66,andromeda_22,Andromeda XXII,21.918330,28.090280,m_033
67,andromeda_23,Andromeda XXIII,22.337500,38.723890,m_031
68,andromeda_24,Andromeda XXIV,19.636250,46.370280,m_031
69,andromeda_25,Andromeda XXV,7.541250,46.861390,m_031
70,andromeda_26,Andromeda XXVI,5.942920,47.911940,m_031
71,andromeda_27,Andromeda XXVII,9.362920,45.386940,m_031
72,andromeda_28,Andromeda XXVIII,338.171667,31.214944,m_031
73,andromeda_29,Andromeda XXIX,359.731670,30.755610,m_031
74,andromeda_35,Andromeda XXXV,6.660833,40.108111,m_031
75,cassiopeia_2,Cassiopeia II,9.144170,49.646940,m_031
76,cassiopeia_3,Cassiopeia III,8.989333,51.560056,m_031
77,ic_0010,IC 10,5.102083,59.291667,m_031
78,lacerta_1,Lacerta I,344.550917,41.306194,m_031
79,lgs_3,LGS 3,15.979167,21.885000,m_031
80,m_032,M 32,10.674125,40.865111,m_031
81,ngc_0147,NGC 147,8.298333,48.507778,m_031
82,ngc_0185,NGC 185,9.741667,48.336111,m_031
83,ngc_0205,NGC 205,10.093750,41.686389,m_031
84,pegasus_5,Pegasus V,349.615833,33.358889,m_031
85,pegasus_7,Pegasus VII,345.455417,32.097778,m_031
86,perseus_1,Perseus I,45.347667,40.984833,m_031
87,pisces_7,Pisces VII,20.419000,26.391000,m_033
88,triangulum_4,Triangulum IV,22.162208,30.984333,m_033
89,agc_749235,AGC749235,186.041250,26.231111,NaN
90,antlia_1,Antlia,151.017083,-27.331111,NaN
91,antlia_b,Antlia B,147.233750,-25.990000,ngc_3109
92,ddo_044,DDO 44,113.547917,66.879722,ngc_2403
93,ddo_099,DDO 99,177.722300,38.880100,NaN
94,ddo_113,DDO 113,183.741250,36.218889,ngc_4214
95,ddo_125,DDO 125,186.920417,43.495556,NaN
96,ddo_147,DDO 147,191.749500,36.477500,NaN
97,ddo_190,DDO 190,216.180833,44.525833,NaN
98,eso_006-001,ESO 006-001,124.847083,-85.145556,NaN
99,eso_274-001,ESO 274-001,228.556250,-46.812500,ngc_5128
100,eso_294-g010,ESO 294-G010,6.639500,-41.855900,ngc_0055
101,eso_410-g005,ESO 410-G005,3.881300,-32.181100,ngc_0055
102,hedgehog_dw1322m2053,Hedgehog,200.695330,-20.898872,NaN
103,ic_3104,IC 3104,184.691667,-79.726111,NaN
104,ic_4662,IC 4662,266.786667,-64.641667,NaN
105,ic_5152,IC 5152,330.673500,-51.296300,NaN
106,kk_153,KK 153,188.757083,58.386611,NaN
107,kk_258,KK 258,340.182917,-30.799722,NaN
108,kkh_98,KKH 98,356.391667,38.717778,NaN
109,kkr_03,KKR 3,211.793750,35.060278,NaN
110,kkr_25,KKR 25,243.450000,54.371111,NaN
111,kks_03,KKs 3,36.185000,-73.514170,NaN
112,kks_53,KKs 53,197.809100,-38.906100,ngc_5128
113,leo_a,Leo A,149.860417,30.746389,NaN
114,leo_m,Leo M,166.339300,25.345290,NaN
115,ngc_0055,NGC 55,3.723333,-39.196667,NaN
116,ngc_0055-dw1,NGC 55-dw1,3.874000,-38.419000,ngc_0055
117,ngc_0300,NGC 300,13.722917,-37.684444,ngc_0055
118,ngc_3109,NGC 3109,150.778750,-26.159722,NaN
119,ngc_4163,NGC 4163,183.038917,36.168917,NaN
120,ngc_4190,NGC 4190,183.435833,36.633333,ngc_4214
121,ngc_4214,NGC 4214,183.913200,36.327400,NaN
122,pavo_1,Pavo,298.751800,-61.075240,NaN
123,pegasus_w,Pegasus W,358.312482,22.101970,NaN
124,phoenix_1,Phoenix,27.775000,-44.445000,NaN
125,sculptor_a,Sculptor A,17.128333,-36.064694,NaN
126,sculptor_b,Sculptor B,16.712083,-35.077500,NaN
127,sculptor_c,Sculptor C,14.467500,-35.852333,ngc_0300
128,tucana_1,Tucana,340.456667,-64.419444,NaN
129,tucana_b,Tucana B,341.752083,-58.407500,NaN
130,ugc_04879,UGC 4879,139.009167,52.840000,NaN
131,ugc_08508,UGC 8508,202.685000,54.910700,NaN
132,ugc_09128,UGC 9128,213.985700,23.055000,NaN
133,ugca_086,UGCA 86,59.951250,67.138611,ic_0342
134,uks_2323_326,UKS 2323-326,351.614583,-32.388889,ngc_0055
135,a0952p69,A0952+69,149.370830,69.272220,m_081
136,agc_112521,AGC 112521,25.282917,27.323889,NaN
137,agc_238890,AGC 238890,203.126250,25.123611,NaN
138,agc_239141,AGC 239141,199.420000,35.466390,NaN
139,agc_749241,AGC 749241,190.007083,26.321944,NaN
140,am_1320-230,AM 1320-230,200.874583,-23.393056,ngc_5128
141,andromeda_04,Andromeda IV,10.634583,40.571667,NaN
142,bedin_1,Bedin 1,287.691042,-59.917292,NaN
143,bk3n,BK3N,148.452083,68.969167,m_081
144,bk5n,BK5N,151.173333,68.256889,m_081
145,bk6n,BK6N,158.632917,66.011667,m_081
146,bts_116,BTS 116,184.738750,28.553056,NaN
147,camelopardalis_a,Camelopardalis A,66.315000,72.805833,ic_0342
148,camelopardalis_b,Camelopardalis B,73.278750,67.099167,ic_0342
149,cassiopea_dirr_1,Cassiopea dIrr 1,31.532917,69.010000,NaN
150,cena-mm-dw01,CenA-MM-Dw1,202.559417,-41.893278,ngc_5128
151,cena-mm-dw02,CenA-MM-Dw2,202.489250,-41.873250,ngc_5128
152,cena-mm-dw03,CenA-MM-Dw3,202.585167,-42.191742,ngc_5128
153,cena-mm-dw04,CenA-MM-Dw4,200.760667,-41.785819,ngc_5128
154,cena-mm-dw05,CenA-MM-Dw5,199.968417,-41.994633,ngc_5128
155,cena-mm-dw06,CenA-MM-Dw6,201.488542,-41.093647,ngc_5128
156,cena-mm-dw07,CenA-MM-Dw7,201.618958,-43.556408,ngc_5128
157,cena-mm-dw08,CenA-MM-Dw8,203.392083,-41.608056,ngc_5128
158,cena-mm-dw09,CenA-MM-Dw9,203.256250,-42.530278,ngc_5128
159,cena-mm-dw10,CenA-MM-Dw10,201.137083,-44.735306,ngc_5128
160,cena-mm-dw11,CenA-MM-Dw11,199.455000,-42.926889,ngc_5128
161,cena_dw1240-42,dw1240-42,190.008333,-42.412222,ngc_5128
162,cena_dw1241-32,dw1241-32,190.362500,-42.895833,ngc_5128
163,cena_dw1243-42,dw1243-42,190.804167,-42.463333,ngc_5128
164,cena_dw1243-42b,dw1243-42b,190.795833,-42.443611,ngc_5128
165,cena_dw1251-40,dw1251-40,192.983333,-40.331389,ngc_5128
166,cena_dw1252-40,dw1252-40,193.004167,-40.365278,ngc_5128
167,cena_dw1252-43,dw1252-43,193.104167,-43.099444,ngc_5128
168,cena_dw1257-41,dw1257-41,194.437500,-41.381111,ngc_5128
169,cena_dw1258-37,dw1258-37,194.620833,-37.122500,ngc_5128
170,cena_dw1301-30,dw1301-30,195.366667,-30.111944,ngc_5128
171,cena_dw1302-40,dw1302-40,195.704167,-40.143056,ngc_5128
172,cena_dw1306-29,dw1306-29,196.700000,-29.891667,ngc_5128
173,cena_dw1312-4218,dw1312-4218,198.093667,-42.311550,ngc_5128
174,cena_dw1312-4244,dw1312-4244,198.045542,-42.745461,ngc_5128
175,cena_dw1312-4246,dw1312-4246,198.042417,-42.780147,ngc_5128
176,cena_dw1313-4211,dw1313-4211,198.392833,-42.185661,ngc_5128
177,cena_dw1313-4214,dw1313-4214,198.401667,-42.235586,ngc_5128
178,cena_dw1313-4246,dw1313-4246,198.178625,-42.780714,ngc_5128
179,cena_dw1314-28,dw1314-28,198.508333,-28.203333,ngc_5128
180,cena_dw1314-4142,dw1314-4142,198.686750,-41.707853,ngc_5128
181,cena_dw1314-4204,dw1314-4204,198.534042,-42.069031,ngc_5128
182,cena_dw1314-4230,dw1314-4230,198.591375,-42.511631,ngc_5128
183,cena_dw1315-4232,dw1315-4232,198.762417,-42.538272,ngc_5128
184,cena_dw1315-4309,dw1315-4309,198.891542,-43.157550,ngc_5128
185,cena_dw1316-4224,dw1316-4224,199.176125,-42.401478,ngc_5128
186,cena_dw1318-21,dw1318-21,199.516667,-21.885000,ngc_5128
187,cena_dw1318-4233,dw1318-4233,199.523292,-42.560306,ngc_5128
188,cena_dw1319-4203,dw1319-4203,199.838583,-42.060761,ngc_5128
189,cena_dw1321-27,dw1321-27,200.283333,-27.748889,ngc_5128
190,cena_dw1322-27,dw1322-27,200.525000,-27.579167,ngc_5128
191,cena_dw1322-39,dw1322-39,200.655800,-39.908400,ngc_5128
192,cena_dw1323-40a,dw1323-40a,201.242100,-40.762200,ngc_5128
193,cena_dw1323-40b,dw1323-40b,201.000000,-40.836700,ngc_5128
194,cena_dw1325-33,dw1325-33,201.420833,-33.006944,ngc_5128
195,cena_dw1326-29,dw1326-29,201.516667,-29.404444,ngc_5128
196,cena_dw1326-35,dw1326-35,201.683333,-35.083333,ngc_5128
197,cena_dw1326-37,dw1326-37,201.591667,-37.385556,ngc_5128
198,cena_dw1329-32,dw1329-32,202.491667,-32.496111,ngc_5128
199,cena_dw1329-45,dw1329-45,202.291667,-45.175278,ngc_5128
200,cena_dw1330-32,dw1330-32,202.725000,-32.305833,ngc_5128
201,cena_dw1330-33,dw1330-33,202.516667,-33.835000,ngc_5128
202,cena_dw1330-34,dw1330-34,202.508333,-34.003889,ngc_5128
203,cena_dw1330-38,dw1330-38,202.670833,-38.167500,ngc_5128
204,cena_dw1331-40,dw1331-40,202.858333,-40.263056,ngc_5128
205,cena_dw1335-29,dw1335-29,203.945417,-29.706222,m_083
206,cena_dw1336-44,dw1336-44,204.183333,-44.447222,ngc_5128
207,cena_dw1337-33,dw1337-33,204.258333,-33.523611,ngc_5128
208,cena_dw1337-41,dw1337-41,204.479167,-41.903056,ngc_5128
209,cena_dw1340-30,dw1340-30,205.079167,-30.359722,m_083
210,cena_dw1341-29,dw1341-29,205.334167,-29.567500,ngc_5264
211,cena_dw1341-33,dw1341-33,205.304167,-33.825000,ngc_5128
212,cena_dw1341-43,dw1341-43,205.404170,-43.855000,ngc_5128
213,cena_dw1342-43,dw1342-43,205.682500,-43.255861,ngc_5128
214,cena_dw1343-34,dw1343-34,205.954167,-34.935278,ngc_5128
215,cena_dw1357-28,dw1357-28,209.250000,-28.920833,ngc_5128
216,cena_dw1401-32,dw1401-32,210.354167,-32.629444,ngc_5128
217,cena_dw1403-33,dw1403-33,210.825000,-33.403889,ngc_5128
218,cena_dw1406-29,dw1406-29,211.670833,-29.136111,ngc_5128
219,cena_dw1409-33,dw1409-33,212.262500,-33.827778,ngc_5128
220,cena_dw1410-34,dw1410-34,212.695833,-34.868611,ngc_5128
221,cena_dw1413-34,dw1413-34,213.283333,-34.392500,ngc_5128
222,cena_dw1415-32,dw1415-32,213.920833,-32.572500,ngc_5128
223,cena_ucd-fluffy,Fluffy,199.545362,-44.157251,ngc_5128
224,cena_ucd-kv19-212,KV19-212,200.790847,-43.874459,ngc_5128
225,cena_ucd-kv19-271,KV19-271,201.296298,-43.509212,ngc_5128
226,cena_ucd-kv19-329,KV19-329,201.672201,-42.703936,ngc_5128
227,cena_ucd-kv19-442,KV19-442,202.432394,-42.391404,ngc_5128
228,centaurus_n,Centaurus N,207.038300,-47.565000,ngc_5128
229,cepheus_1,Cepheus1,312.790417,56.890000,ngc_6946
230,cgcg_189m050,CGCG 189-050,199.270420,37.952500,NaN
231,cgcg_217m018,CGCG 217-018,198.215833,40.543056,ngc_5055
232,ddo_006,DDO 6,12.454000,-21.017000,ngc_0253
233,ddo_046,DDO 46,115.357500,40.112500,NaN
234,ddo_053,DDO 53,128.536200,66.177100,m_081
235,ddo_078,DDO 78,156.616250,67.656667,m_081
236,ddo_082,DDO 82,157.645830,70.619440,m_081
237,ddo_126,DDO 126,186.771250,37.142500,NaN
238,ddo_127,DDO 127,187.118750,37.233333,NaN
239,ddo_133,DDO 133,188.227000,31.538900,NaN
240,ddo_154,DDO 154,193.521670,27.148610,NaN
241,ddo_165,DDO 165,196.611670,67.704170,NaN
242,ddo_167,DDO 167,198.345000,46.319720,NaN
243,ddo_168,DDO 168,198.619167,45.919444,NaN
244,ddo_169,DDO 169,198.877920,47.496390,NaN
245,ddo_169_nw,DDO 169NW,198.833750,47.543611,NaN
246,ddo_181,DDO 181,204.973600,40.739900,NaN
247,ddo_183,DDO 183,207.712100,38.019800,m_094
248,ddo_226,DDO 226,10.765830,-22.250280,NaN
249,donatiello_1,Donatiello I,17.918208,34.600889,NaN
250,donatiello_3,Donatiello III,17.352400,-27.347070,ngc_0253
251,donatiello_4,Donatiello IV,11.762550,-21.680710,ngc_0253
252,donatiello_5,Donatiello V,8.243000,-23.279194,ngc_0253
253,donatiello_6,Donatiello VI,8.732000,-21.994810,ngc_0253
254,donatiello_7,Donatiello VII,9.395083,-29.479100,ngc_0253
255,donatiello_8,Donatiello VIII,10.145417,-20.557111,ngc_0253
256,donatiello_9,Donatiello IX,10.676000,-23.769610,ngc_0253
257,dw0741p4005,dw0741p4005,115.392400,40.084300,ddo_046
258,dw1008p7038b,dw1008p7038b,152.200500,70.645600,ugc_05423
259,dw1009p7032,dw1009p7032,152.394200,70.548900,ugc_05423
260,dw1242p4115,dw1242p4115,190.547000,41.252500,ngc_4618
261,dw1250p5056,dw1250p5056,192.735400,50.934600,ngc_4707
262,dw1343+58,dw1343+58,205.779167,58.227778,NaN
263,dw_0128-4116,Dw0128-4116,22.179167,-41.276111,ngc_0625
264,dw_0312-6643,Dw0312-6643,48.087917,-66.721111,ngc_1313
265,dw_1105-3041,Dw1105-3041,166.447917,-30.688611,ngc_3621
266,dw_1128-3225,Dw1128-3225,172.242083,-32.423056,ngc_3621
267,dw_1321-2202,Dw1321-2202,200.267083,-22.033056,ngc_5068
268,dw_1324-2017,Dw1324-2017,201.225833,-20.298056,ngc_5068
269,dw_1844-6232,Dw1844-6232,281.227083,-62.546944,ngc_6744
270,dw_1851-6355,Dw1851-6355,282.929167,-63.920000,ngc_6744
271,dw_1851-6356,Dw1851-6356,282.925833,-63.935000,ngc_6744
272,dw_1851-6400,Dw1851-6400,282.792917,-64.008056,ngc_6744
273,dw_1851-6511,Dw1851-6511,282.912917,-65.193889,ngc_6744
274,dw_2140-5544,Dw2140-5544,325.247083,-55.746944,ngc_7090
275,dw_2256-4107,Dw2256-4107,344.057917,-41.128611,ngc_7424
276,dw_2256-4250,Dw2256-4250,344.159167,-42.843889,ngc_7424
277,eso_059-001,ESO 059-001,112.830417,-68.186111,NaN
278,eso_104-044,ESO104-044,287.846250,-64.219167,ngc_6744
279,eso_115-021,ESO 115-021,39.437500,-61.341111,NaN
280,eso_121-020,ESO 121-020,93.977083,-57.726389,NaN
281,eso_137-018,ESO 137-018,245.247083,-60.487500,NaN
282,eso_154-023,ESO 154-023,44.210000,-54.573056,NaN
283,eso_199-007,ESO 199-007,44.517083,-49.382500,NaN
284,eso_215-009,ESO 215-009,164.375833,-48.178889,ngc_5128
285,eso_219-010,ESO219-010,194.040000,-50.143889,ngc_5128
286,eso_222-010,ESO 222-010,218.762500,-49.421667,NaN
287,eso_245-005,ESO 245-005,26.265000,-43.598100,NaN
288,eso_269-037,ESO 269-037,195.888293,-46.586861,ngc_5128
289,eso_269-058,ESO 269-058,197.637083,-46.990830,ngc_5128
290,eso_269-066,ESO 269-066,198.288333,-44.890000,ngc_5128
291,eso_272-025,ESO 272-025,220.856250,-44.705278,NaN
292,eso_273-014,ESO 273-014,224.626250,-47.698611,NaN
293,eso_290-028,ESO 290-028,344.288333,-42.805000,ngc_7424
294,eso_300-016,ESO 300-016,47.543750,-40.003056,ngc_1291
295,eso_301-007,ESO 301-007,50.352000,-41.998000,ngc_1291
296,eso_301-010,ESO 301-010,50.817000,-40.678000,ngc_1291
297,eso_320-014,ESO 320-014,174.472500,-39.220556,NaN
298,eso_321-014,ESO 321-014,183.456667,-38.231389,ngc_5128
299,eso_324-024,ESO 324-024,201.905830,-41.480560,ngc_5128
300,eso_325-011,ESO 325-011,206.252083,-41.861111,ngc_5128
301,eso_346-007,ESO 346-007,343.348750,-38.799722,ngc_7424
302,eso_349-031,ESO 349-031,2.055417,-34.578333,ngc_7793
303,eso_379-007,ESO 379-007,178.679167,-33.558056,NaN
304,eso_379-024,ESO 379-024,181.236250,-35.743056,NaN
305,eso_381-018,ESO 381-018,191.175000,-35.966389,ngc_5128
306,eso_381-020,ESO 381-020,191.500000,-33.836944,ngc_5128
307,eso_383-087,ESO 383-087,207.320833,-36.063333,ngc_5128
308,eso_384-016,ESO 384-016,209.255708,-35.332972,ngc_5128
309,eso_443-009,ESO 443-009,193.725000,-28.340833,ngc_5128
310,eso_444-084,ESO 444-084,204.334167,-28.046111,m_083
311,eso_472-015,ESO 472-015,1.701667,-24.944722,ngc_0024
312,f8d1,F8D1,146.191458,67.441028,m_081
313,fm_1,FM1,146.291667,68.765000,m_081
314,garland,GARLAND,150.925000,68.693000,ngc_3077
315,ghosts_1,GHOSTS I,148.307083,69.500731,NaN
316,grapes,Grapes,178.023333,54.792222,NaN
317,hideep_j1337-3320,HIDEEP J1337-3320,204.252500,-33.363056,m_083
318,hijass_j1021p6842,HIJASS J1021+6842,155.250830,68.700000,m_081
319,hipass_j1131-31,HIPASS J1131-31,172.894167,-31.674528,ngc_3621
320,hipass_j1133-32,HIPASS J1133-32,173.295833,-32.961944,NaN
321,hipass_j1247-77,HIPASS J1247-77,191.890842,-77.582623,NaN
322,hipass_j1337-39,HIPASS J1337-39,204.354583,-39.897778,ngc_5128
323,hipass_j1348-37,HIPASS J1348-37,207.139792,-37.967944,ngc_5128
324,hipass_j1351-47,HIPASS J1351-47,207.841667,-47.000000,NaN
325,hipass_j1441-62,HIPASS J1441-62,220.427917,-62.767222,NaN
326,hizoa_j1149-62,HIZOA J1149-62,177.410000,-62.183889,NaN
327,hizss-021,HIZSS-021,116.568750,-28.469722,NaN
328,holmberg_1,Holmberg I,145.134583,71.186389,m_081
329,holmberg_2,Holmberg II,124.766667,70.714167,m_081
330,holmberg_4,Holm IV,208.689000,53.904000,m_101
331,holmberg_9,Holmberg IX,149.385000,69.043060,m_081
332,hydrus_a,Hydrus A,56.193333,-70.354389,NaN
333,ic_0239,IC239,39.116000,38.969000,ngc_1023
334,ic_1959,IC1959,53.299167,-50.410556,NaN
335,ic_2574,IC 2574,157.093000,68.416000,m_081
336,ic_3571,IC3571,189.084000,26.084000,ngc_4565
337,ic_3687,IC 3687,190.563000,38.503000,m_094
338,ic_3840,IC 3840,192.942083,21.735278,ngc_4826
339,ic_4182,IC 4182,196.455417,37.605833,NaN
340,ic_4247,IC 4247,201.685000,-30.362500,m_083
341,ic_4316,IC 4316,205.075417,-28.894444,m_083
342,ic_5052,IC 5052,313.025833,-69.203889,NaN
343,ikn,IKN,152.020833,68.421139,m_081
344,jkb_083,JKB83,148.956900,69.332600,m_081
345,kamino_1,Kamino,63.955060,-60.731060,NaN
346,kdg_052,KDG 52,125.985400,71.030800,m_081
347,kdg_061,KDG 61,149.263333,68.592889,m_081
348,kdg_063,KDG 63,151.280420,66.555000,m_081
349,kdg_064,KDG 64,151.758333,67.828722,m_081
350,kdg_073,KDG 73,163.233383,69.547753,m_081
351,kdg_074,KDG 74,165.590830,70.263890,m_081
352,kk_016,KK 16,28.835833,27.954167,ngc_0784
353,kk_017,KK 17,330.042042,28.831169,NaN
354,kk_027,KK 27,50.262500,-66.319722,NaN
355,kk_035,KK 35,56.302500,67.863889,NaN
356,kk_069,KK 69,133.211250,33.797778,ngc_2683
357,kk_070,KK 70,133.847083,33.559000,ngc_2683
358,kk_077,KK 77,147.541670,67.506700,m_081
359,kk_101,KK 101,169.185833,-32.651111,ngc_3621
360,kk_108,KK 108,175.015000,46.478611,NaN
361,kk_109,KK 109,176.796667,43.671944,NaN
362,kk_132,KK 132,184.777083,47.730833,ngc_4248
363,kk_135,KK 135,184.894498,58.043948,NaN
364,kk_144,KK 144,186.370584,28.484583,NaN
365,kk_160,KK 160,190.989000,43.662000,m_094
366,kk_165,KK 165,192.219583,31.970278,ngc_4631
367,kk_166,KK 166,192.300650,35.612580,NaN
368,kk_177,KK 177,195.674583,21.997500,ngc_4826
369,kk_182,KK 182,196.258333,-40.082778,ngc_5128
370,kk_186,KK 186,197.440000,-23.543056,ngc_5068
371,kk_189,KK 189,198.187500,-41.831944,ngc_5128
372,kk_191,KK 191,198.415417,42.044167,ngc_5055
373,kk_193,KK 193,198.874170,41.502230,ngc_5055
374,kk_195,KK 195,200.284167,-31.529722,m_083

## MW Dwarf Galaxies
612 dwarf galaxies might be a little too much lol.

In [7]:
#Find all MW dwarf galaxies with declination above 20 degrees above/below galactic plane

mw = dsph_mw[abs(dsph_mw['dec']) >= 20.0]
print(len(mw))
#print(mw)

39

In [8]:
lvdb.add_column(mw,'location','name_discovery', col_type='U25')

In [9]:
mw['key','name','ra','dec','host'].to_pandas() #For some reason 'type' to find the type of dwarf does not work.

                 key               name          ra        dec host
0           antlia_2          Antlia II  143.807900 -36.699100   mw
1           bootes_3         Bootes III  209.300000  26.800000   mw
2           bootes_4          Bootes IV  233.689000  43.726000   mw
3           bootes_5           Bootes V  213.909000  32.914000   mw
4   canes_venatici_1   Canes Venatici I  202.009100  33.552100   mw
5   canes_venatici_2  Canes Venatici II  194.292700  34.322600   mw
6           carina_1             Carina  100.406500 -50.959300   mw
7           carina_4          Carina IV  104.046000 -63.319000   mw
8        centaurus_1        Centaurus I  189.590800 -40.904300   mw
9          columba_1          Columba I   82.856960 -28.042530   mw
10  coma_berenices_1     Coma Berenices  186.745400  23.906900   mw
11           draco_1              Draco  260.068400  57.918500   mw
12           draco_2           Draco II  238.198333  64.565278   mw
13        eridanus_2        Eridanus II   56.092500 -43.532900   mw
14          fornax_1             Fornax   39.958300 -34.499700   mw
15            grus_1             Grus I  344.166000 -50.168000   mw
16            grus_2            Grus II  331.025000 -46.442000   mw
17      horologium_2      Horologium II   49.131000 -50.009000   mw
18           hydra_2           Hydra II  185.428600 -31.972800   mw
19             leo_2             Leo II  168.362700  22.152900   mw
20             leo_6             Leo VI  171.077000  24.874000   mw
21       leo_minor_1        Leo Minor I  164.261000  28.875000   mw
22               lmc                LMC   78.760000 -69.190000   mw
23         pegasus_4         Pegasus IV  328.539000  26.620000   mw
24         phoenix_3        Phoenix III   26.711000 -41.428000   mw
25          pictor_1           Pictor I   70.947500 -50.283056   mw
26       reticulum_3      Reticulum III   56.360000 -60.450000   mw
27     sagittarius_1        Sagittarius  284.095166 -30.549887   mw
28        sculptor_1           Sculptor   15.018300 -33.718600   mw
29           segue_2            Segue 2   34.822600  20.162400   mw
30      triangulum_2      Triangulum II   33.315500  36.169100   mw
31          tucana_2          Tucana II  342.979600 -58.568900   mw
32          tucana_3         Tucana III  359.107500 -59.583320   mw
33          tucana_4          Tucana IV    0.717000 -60.830000   mw
34          tucana_5           Tucana V  354.347000 -63.266000   mw
35      ursa_major_1       Ursa Major I  158.770600  51.947900   mw
36      ursa_major_2      Ursa Major II  132.872600  63.133500   mw
37      ursa_minor_1         Ursa Minor  227.242000  67.222100   mw
38         willman_1          Willman 1  162.343600  51.050100   mw

## For LMC

In [10]:
#Comb through file in 'host' category, only accept dwarfs with * as host
lmc = comb_all_local[comb_all_local['host'] == 'lmc']

In [11]:
lvdb.add_column(lmc,'location','name_discovery', col_type='U25')
lmc['key','name','ra','dec','host'].to_pandas()

            key          name        ra      dec host
0      carina_2     Carina II  114.1066 -57.9991  lmc
1      carina_3    Carina III  114.6298 -57.8997  lmc
2  horologium_1  Horologium I   43.8755 -54.1174  lmc
3      hydrus_1      Hydrus I   37.3890 -79.3089  lmc
4     phoenix_2    Phoenix II  354.9919 -54.4019  lmc
5      pictor_2     Pictor II  101.1750 -59.9010  lmc
6   reticulum_2  Reticulum II   53.9203 -54.0513  lmc
7           smc           SMC   16.2500 -72.4200  lmc

# For dwarf_local_field.csv file
This file contains "dwarf galaxies outside of MW/M31 within the Local Field to a distance of ~ 3 Mpc. This is an extension of galaxies from McConnachie 2012 compilation."

In [12]:
#Find all local field dwarf galaxies with declination above 20 degrees above/below galactic plane

local_field = comb_local_field[abs(comb_local_field['dec'])>= 20.0]
print(len(local_field))
#print(local_field)

46

In [13]:
lvdb.add_column(local_field,'location','name_discovery', col_type='U25')
local_field['key','name','ra','dec','host'].to_pandas()

                     key          name          ra        dec      host
0             agc_749235     AGC749235  186.041250  26.231111       NaN
1               antlia_1        Antlia  151.017083 -27.331111       NaN
2               antlia_b      Antlia B  147.233750 -25.990000  ngc_3109
3                ddo_044        DDO 44  113.547917  66.879722  ngc_2403
4                ddo_099        DDO 99  177.722300  38.880100       NaN
5                ddo_113       DDO 113  183.741250  36.218889  ngc_4214
6                ddo_125       DDO 125  186.920417  43.495556       NaN
7                ddo_147       DDO 147  191.749500  36.477500       NaN
8                ddo_190       DDO 190  216.180833  44.525833       NaN
9            eso_006-001   ESO 006-001  124.847083 -85.145556       NaN
10           eso_274-001   ESO 274-001  228.556250 -46.812500  ngc_5128
11          eso_294-g010  ESO 294-G010    6.639500 -41.855900  ngc_0055
12          eso_410-g005  ESO 410-G005    3.881300 -32.181100  ngc_0055
13  hedgehog_dw1322m2053      Hedgehog  200.695330 -20.898872       NaN
14               ic_3104       IC 3104  184.691667 -79.726111       NaN
15               ic_4662       IC 4662  266.786667 -64.641667       NaN
16               ic_5152       IC 5152  330.673500 -51.296300       NaN
17                kk_153        KK 153  188.757083  58.386611       NaN
18                kk_258        KK 258  340.182917 -30.799722       NaN
19                kkh_98        KKH 98  356.391667  38.717778       NaN
20                kkr_03         KKR 3  211.793750  35.060278       NaN
21                kkr_25        KKR 25  243.450000  54.371111       NaN
22                kks_03         KKs 3   36.185000 -73.514170       NaN
23                kks_53        KKs 53  197.809100 -38.906100  ngc_5128
24                 leo_a         Leo A  149.860417  30.746389       NaN
25                 leo_m         Leo M  166.339300  25.345290       NaN
26              ngc_0055        NGC 55    3.723333 -39.196667       NaN
27          ngc_0055-dw1    NGC 55-dw1    3.874000 -38.419000  ngc_0055
28              ngc_0300       NGC 300   13.722917 -37.684444  ngc_0055
29              ngc_3109      NGC 3109  150.778750 -26.159722       NaN
30              ngc_4163      NGC 4163  183.038917  36.168917       NaN
31              ngc_4190      NGC 4190  183.435833  36.633333  ngc_4214
32              ngc_4214      NGC 4214  183.913200  36.327400       NaN
33                pavo_1          Pavo  298.751800 -61.075240       NaN
34             pegasus_w     Pegasus W  358.312482  22.101970       NaN
35             phoenix_1       Phoenix   27.775000 -44.445000       NaN
36            sculptor_a    Sculptor A   17.128333 -36.064694       NaN
37            sculptor_b    Sculptor B   16.712083 -35.077500       NaN
38            sculptor_c    Sculptor C   14.467500 -35.852333  ngc_0300
39              tucana_1        Tucana  340.456667 -64.419444       NaN
40              tucana_b      Tucana B  341.752083 -58.407500       NaN
41             ugc_04879      UGC 4879  139.009167  52.840000       NaN
42             ugc_08508      UGC 8508  202.685000  54.910700       NaN
43             ugc_09128      UGC 9128  213.985700  23.055000       NaN
44              ugca_086       UGCA 86   59.951250  67.138611   ic_0342
45          uks_2323_326  UKS 2323-326  351.614583 -32.388889  ngc_0055

# New List

Keep dwarf galaxies only with host as MW or generally in Local Group. M31 and M33 dwarfs might have signals that are difficult to disentangle from their respective host.

In [14]:
#Redefine Dwarf Galaxies in the Local Field that don't have MW/M31/M33 as host
MW = mw['key','name','ra','dec','host'].to_pandas()
LF = local_field['key','name','ra','dec','host'].to_pandas()
LMC = lmc['key','name','ra','dec','host'].to_pandas()

#If we want to keep all Dwarf Galaxies in Local Group with MW and other galaxies as host + w/o host
list_1 = pd.concat([MW, LMC, LF], ignore_index=True)
print(len(list_1))
display(list_1)

93

                     key               name          ra        dec      host
0               antlia_2          Antlia II  143.807900 -36.699100        mw
1               bootes_3         Bootes III  209.300000  26.800000        mw
2               bootes_4          Bootes IV  233.689000  43.726000        mw
3               bootes_5           Bootes V  213.909000  32.914000        mw
4       canes_venatici_1   Canes Venatici I  202.009100  33.552100        mw
5       canes_venatici_2  Canes Venatici II  194.292700  34.322600        mw
6               carina_1             Carina  100.406500 -50.959300        mw
7               carina_4          Carina IV  104.046000 -63.319000        mw
8            centaurus_1        Centaurus I  189.590800 -40.904300        mw
9              columba_1          Columba I   82.856960 -28.042530        mw
10      coma_berenices_1     Coma Berenices  186.745400  23.906900        mw
11               draco_1              Draco  260.068400  57.918500        mw
12               draco_2           Draco II  238.198333  64.565278        mw
13            eridanus_2        Eridanus II   56.092500 -43.532900        mw
14              fornax_1             Fornax   39.958300 -34.499700        mw
15                grus_1             Grus I  344.166000 -50.168000        mw
16                grus_2            Grus II  331.025000 -46.442000        mw
17          horologium_2      Horologium II   49.131000 -50.009000        mw
18               hydra_2           Hydra II  185.428600 -31.972800        mw
19                 leo_2             Leo II  168.362700  22.152900        mw
20                 leo_6             Leo VI  171.077000  24.874000        mw
21           leo_minor_1        Leo Minor I  164.261000  28.875000        mw
22                   lmc                LMC   78.760000 -69.190000        mw
23             pegasus_4         Pegasus IV  328.539000  26.620000        mw
24             phoenix_3        Phoenix III   26.711000 -41.428000        mw
25              pictor_1           Pictor I   70.947500 -50.283056        mw
26           reticulum_3      Reticulum III   56.360000 -60.450000        mw
27         sagittarius_1        Sagittarius  284.095166 -30.549887        mw
28            sculptor_1           Sculptor   15.018300 -33.718600        mw
29               segue_2            Segue 2   34.822600  20.162400        mw
30          triangulum_2      Triangulum II   33.315500  36.169100        mw
31              tucana_2          Tucana II  342.979600 -58.568900        mw
32              tucana_3         Tucana III  359.107500 -59.583320        mw
33              tucana_4          Tucana IV    0.717000 -60.830000        mw
34              tucana_5           Tucana V  354.347000 -63.266000        mw
35          ursa_major_1       Ursa Major I  158.770600  51.947900        mw
36          ursa_major_2      Ursa Major II  132.872600  63.133500        mw
37          ursa_minor_1         Ursa Minor  227.242000  67.222100        mw
38             willman_1          Willman 1  162.343600  51.050100        mw
39              carina_2          Carina II  114.106600 -57.999100       lmc
40              carina_3         Carina III  114.629800 -57.899700       lmc
41          horologium_1       Horologium I   43.875500 -54.117400       lmc
42              hydrus_1           Hydrus I   37.389000 -79.308900       lmc
43             phoenix_2         Phoenix II  354.991900 -54.401900       lmc
44              pictor_2          Pictor II  101.175000 -59.901000       lmc
45           reticulum_2       Reticulum II   53.920300 -54.051300       lmc
46                   smc                SMC   16.250000 -72.420000       lmc
47            agc_749235          AGC749235  186.041250  26.231111       NaN
48              antlia_1             Antlia  151.017083 -27.331111       NaN
49              antlia_b           Antlia B  147.233750 -25.990000  ngc_3109
50               ddo_044             DDO 44  113.547917  66.879722  ngc_2403
51               ddo_099             DDO 99  177.722300  38.880100       NaN
52               ddo_113            DDO 113  183.741250  36.218889  ngc_4214
53               ddo_125            DDO 125  186.920417  43.495556       NaN
54               ddo_147            DDO 147  191.749500  36.477500       NaN
55               ddo_190            DDO 190  216.180833  44.525833       NaN
56           eso_006-001        ESO 006-001  124.847083 -85.145556       NaN
57           eso_274-001        ESO 274-001  228.556250 -46.812500  ngc_5128
58          eso_294-g010       ESO 294-G010    6.639500 -41.855900  ngc_0055
59          eso_410-g005       ESO 410-G005    3.881300 -32.181100  ngc_0055
60  hedgehog_dw1322m2053           Hedgehog  200.695330 -20.898872       NaN
61               ic_3104            IC 3104  184.691667 -79.726111       NaN
62               ic_4662            IC 4662  266.786667 -64.641667       NaN
63               ic_5152            IC 5152  330.673500 -51.296300       NaN
64                kk_153             KK 153  188.757083  58.386611       NaN
65                kk_258             KK 258  340.182917 -30.799722       NaN
66                kkh_98             KKH 98  356.391667  38.717778       NaN
67                kkr_03              KKR 3  211.793750  35.060278       NaN
68                kkr_25             KKR 25  243.450000  54.371111       NaN
69                kks_03              KKs 3   36.185000 -73.514170       NaN
70                kks_53             KKs 53  197.809100 -38.906100  ngc_5128
71                 leo_a              Leo A  149.860417  30.746389       NaN
72                 leo_m              Leo M  166.339300  25.345290       NaN
73              ngc_0055             NGC 55    3.723333 -39.196667       NaN
74          ngc_0055-dw1         NGC 55-dw1    3.874000 -38.419000  ngc_0055
75              ngc_0300            NGC 300   13.722917 -37.684444  ngc_0055
76              ngc_3109           NGC 3109  150.778750 -26.159722       NaN
77              ngc_4163           NGC 4163  183.038917  36.168917       NaN
78              ngc_4190           NGC 4190  183.435833  36.633333  ngc_4214
79              ngc_4214           NGC 4214  183.913200  36.327400       NaN
80                pavo_1               Pavo  298.751800 -61.075240       NaN
81             pegasus_w          Pegasus W  358.312482  22.101970       NaN
82             phoenix_1            Phoenix   27.775000 -44.445000       NaN
83            sculptor_a         Sculptor A   17.128333 -36.064694       NaN
84            sculptor_b         Sculptor B   16.712083 -35.077500       NaN
85            sculptor_c         Sculptor C   14.467500 -35.852333  ngc_0300
86              tucana_1             Tucana  340.456667 -64.419444       NaN
87              tucana_b           Tucana B  341.752083 -58.407500       NaN
88             ugc_04879           UGC 4879  139.009167  52.840000       NaN
89             ugc_08508           UGC 8508  202.685000  54.910700       NaN
90             ugc_09128           UGC 9128  213.985700  23.055000       NaN
91              ugca_086            UGCA 86   59.951250  67.138611   ic_0342
92          uks_2323_326       UKS 2323-326  351.614583 -32.388889  ngc_0055

## Only MW Satellites and Dwarf Galaxies without Host

Assume we only want to keep the dwarf galaxies that have MW/LMC as host, as well as other dwarf galaxies in the Local Group that don't have a host.

In [15]:
#Dwarf Galaxies w/o host in LG
LF = LF[LF['host'].isna()]
print(len(LF))

33

In [16]:
#Keep all Dwarf Galaxies in Local Group with MW as host + w/o host
list_2 = pd.concat([MW, LMC, LF], ignore_index=True)
print(len(list_2))
display(list_2)

80

                     key               name          ra        dec host
0               antlia_2          Antlia II  143.807900 -36.699100   mw
1               bootes_3         Bootes III  209.300000  26.800000   mw
2               bootes_4          Bootes IV  233.689000  43.726000   mw
3               bootes_5           Bootes V  213.909000  32.914000   mw
4       canes_venatici_1   Canes Venatici I  202.009100  33.552100   mw
5       canes_venatici_2  Canes Venatici II  194.292700  34.322600   mw
6               carina_1             Carina  100.406500 -50.959300   mw
7               carina_4          Carina IV  104.046000 -63.319000   mw
8            centaurus_1        Centaurus I  189.590800 -40.904300   mw
9              columba_1          Columba I   82.856960 -28.042530   mw
10      coma_berenices_1     Coma Berenices  186.745400  23.906900   mw
11               draco_1              Draco  260.068400  57.918500   mw
12               draco_2           Draco II  238.198333  64.565278   mw
13            eridanus_2        Eridanus II   56.092500 -43.532900   mw
14              fornax_1             Fornax   39.958300 -34.499700   mw
15                grus_1             Grus I  344.166000 -50.168000   mw
16                grus_2            Grus II  331.025000 -46.442000   mw
17          horologium_2      Horologium II   49.131000 -50.009000   mw
18               hydra_2           Hydra II  185.428600 -31.972800   mw
19                 leo_2             Leo II  168.362700  22.152900   mw
20                 leo_6             Leo VI  171.077000  24.874000   mw
21           leo_minor_1        Leo Minor I  164.261000  28.875000   mw
22                   lmc                LMC   78.760000 -69.190000   mw
23             pegasus_4         Pegasus IV  328.539000  26.620000   mw
24             phoenix_3        Phoenix III   26.711000 -41.428000   mw
25              pictor_1           Pictor I   70.947500 -50.283056   mw
26           reticulum_3      Reticulum III   56.360000 -60.450000   mw
27         sagittarius_1        Sagittarius  284.095166 -30.549887   mw
28            sculptor_1           Sculptor   15.018300 -33.718600   mw
29               segue_2            Segue 2   34.822600  20.162400   mw
30          triangulum_2      Triangulum II   33.315500  36.169100   mw
31              tucana_2          Tucana II  342.979600 -58.568900   mw
32              tucana_3         Tucana III  359.107500 -59.583320   mw
33              tucana_4          Tucana IV    0.717000 -60.830000   mw
34              tucana_5           Tucana V  354.347000 -63.266000   mw
35          ursa_major_1       Ursa Major I  158.770600  51.947900   mw
36          ursa_major_2      Ursa Major II  132.872600  63.133500   mw
37          ursa_minor_1         Ursa Minor  227.242000  67.222100   mw
38             willman_1          Willman 1  162.343600  51.050100   mw
39              carina_2          Carina II  114.106600 -57.999100  lmc
40              carina_3         Carina III  114.629800 -57.899700  lmc
41          horologium_1       Horologium I   43.875500 -54.117400  lmc
42              hydrus_1           Hydrus I   37.389000 -79.308900  lmc
43             phoenix_2         Phoenix II  354.991900 -54.401900  lmc
44              pictor_2          Pictor II  101.175000 -59.901000  lmc
45           reticulum_2       Reticulum II   53.920300 -54.051300  lmc
46                   smc                SMC   16.250000 -72.420000  lmc
47            agc_749235          AGC749235  186.041250  26.231111  NaN
48              antlia_1             Antlia  151.017083 -27.331111  NaN
49               ddo_099             DDO 99  177.722300  38.880100  NaN
50               ddo_125            DDO 125  186.920417  43.495556  NaN
51               ddo_147            DDO 147  191.749500  36.477500  NaN
52               ddo_190            DDO 190  216.180833  44.525833  NaN
53           eso_006-001        ESO 006-001  124.847083 -85.145556  NaN
54  hedgehog_dw1322m2053           Hedgehog  200.695330 -20.898872  NaN
55               ic_3104            IC 3104  184.691667 -79.726111  NaN
56               ic_4662            IC 4662  266.786667 -64.641667  NaN
57               ic_5152            IC 5152  330.673500 -51.296300  NaN
58                kk_153             KK 153  188.757083  58.386611  NaN
59                kk_258             KK 258  340.182917 -30.799722  NaN
60                kkh_98             KKH 98  356.391667  38.717778  NaN
61                kkr_03              KKR 3  211.793750  35.060278  NaN
62                kkr_25             KKR 25  243.450000  54.371111  NaN
63                kks_03              KKs 3   36.185000 -73.514170  NaN
64                 leo_a              Leo A  149.860417  30.746389  NaN
65                 leo_m              Leo M  166.339300  25.345290  NaN
66              ngc_0055             NGC 55    3.723333 -39.196667  NaN
67              ngc_3109           NGC 3109  150.778750 -26.159722  NaN
68              ngc_4163           NGC 4163  183.038917  36.168917  NaN
69              ngc_4214           NGC 4214  183.913200  36.327400  NaN
70                pavo_1               Pavo  298.751800 -61.075240  NaN
71             pegasus_w          Pegasus W  358.312482  22.101970  NaN
72             phoenix_1            Phoenix   27.775000 -44.445000  NaN
73            sculptor_a         Sculptor A   17.128333 -36.064694  NaN
74            sculptor_b         Sculptor B   16.712083 -35.077500  NaN
75              tucana_1             Tucana  340.456667 -64.419444  NaN
76              tucana_b           Tucana B  341.752083 -58.407500  NaN
77             ugc_04879           UGC 4879  139.009167  52.840000  NaN
78             ugc_08508           UGC 8508  202.685000  54.910700  NaN
79             ugc_09128           UGC 9128  213.985700  23.055000  NaN

### Issues

When going through the sources that were used in papers, I found that I have filtered out some of the sources they use for their respective analysis. Also, some of the sources that I have not filtered out were omitted sources in specific papers (but not ommited in others). 

1. "A Global Analysis of Dark Matter Signals from 27 Dwarf SpheroidalGalaxies using 11 Years of Fermi-LAT Observations"

- "Removing WILLMAN 1...we consider to 27: AQUARIUS II, BOÖTES I, CANES VENATICI I, CANES VENATICI II, CARINA, CARINA II, COMA BERENICES, DRACO, DRACO II, FORNAX, GRUS I, HERCULES, HOROLOGIUM I, LEO I, LEO II, LEO IV, LEO V, PEGASUS III, PISCES II, RETICULUM II, SCULPTOR, SEGUE 1, SEXTANS, TUCANA II, URSA MAJOR I, URSA MAJOR II, and URSA MINOR.

- Studied are all Milky Way satellites, except Ret II, which needed to be treated differently than the other sources due to "Selecting significantly more data for this comparison was not possible, since PASS 7 was discontinued after week 368 and we want to use the same observation time for both PASS 7 and PASS 8 to enable a meaningful comparison."

- Willman I was removed due to strong evidence for tidal disruption and/or nonequilibrium kinematics, which would inflate velocity dispersions (and overestimate annihilation factor, J).


2. "Searching for dark matter annihilating into light long-lived mediators from stars inside dwarf spheroidal galaxies"

- Sources: Draco II, Segue I, Sagittarius, Hydrus I, Reticulum II, Ursa Major II, Carina II, Bootes II, Willman I, Coma Berenices.

3. "Scaling Relations for Dark Matter Annihilation and Decay Profiles in Dwarf Spheroidal Galaxies"

- Compilation of J/D Factors for MW, M31, and Local Field dSphs.

4. "New dark matter analysis of milky way dwarf satellite galaxies with MADHATV2"

- 54 dSphs, likelihood stack with J-factors?

5."Leo I: the classical dwarf spheroidal galaxy with the highest dark-matter density"

- Leo I

6. "Prospects for dark matter observations in dwarf spheroidal galaxies with the Cherenkov Telescope Array Observatory"

- "From an initial sample of 64 dSphs, eight promising targets are identified – Draco I,
Coma Berenices, Ursa Major II, Ursa Minor and Willman 1 in the North, Reticulum II, Sculptor and Sagittarius II in the South- for which different DM density models yield consistent expectations, leading to robust predictions."

- Narrowed down the best canidates for DM signals, using the following selection criterion: i) Distance selection of $d \leq 100 $kpc (remove dSphs for which we expect low values of $J_{ann}$, leaves us with 35 candidates), ii) Investigate quality and availability of spectro-photometric data (discard those with missing and unreliable data, 14 sources remaining), and iii) Select highest values of $J_{ann}$ (8 targets left).


Next list is me trying to also include the sources they used, such that a reference can be made to those specific papers. I don't believe that the sources that were omitted in certain papers would be neccesarily a problem for us, due to their analysis being heavily dependent on velocity dispersions not being calculated correctly (implying its overestimations in J-factor). Since we are not directly using the J-factor, would it make sense to omit certain DGs based on this reasoning?

## Distance Limiting
Apply a distance selection. CTAO paper does this to weed out dSphs (both cls and ufd) that will naturally have very low annihilation rates due to being quite far away. This is based on Equation 4 in their paper. I think this might be useful in our case, because